image: ubuntu:bionic

stages:
  - test

test:
  stage: test
  script:
    - apt-get update -yqq
    - apt-get install -y -q php7.2-cli php7.2-xml php7.2-mbstring php7.2-curl zip unzip curl
    - php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - ./composer.phar install
    - ./vendor/bin/phpunit Test/
